PROJECT_ROOT_DIR      =  ..\..
PROJECT_OUTPUT_DIR    =  __output.ddk

MODULE_ROOT_STEP      =  $(PROJECT_ROOT_DIR)\$(MODULE_DIR_STEP)
MODULE_OUTPUT_DIR     =  $(MODULE_ROOT_STEP)\$(PROJECT_OUTPUT_DIR)\$(BUILD_ALT_DIR)

