set "PROGRAMS_FOLDER.X86=%ProgramFiles%"
if '%PROCESSOR_ARCHITECTURE%'=='x86' (
  set "PROGRAMS_FOLDER.X86=%ProgramFiles%"
) else if '%PROCESSOR_ARCHITECTURE%'=='AMD64' (
  set "PROGRAMS_FOLDER.X86=%ProgramFiles(x86)%"
)

if not defined WINSDK8.1_FOLDER set "WINSDK8.1_FOLDER=%PROGRAMS_FOLDER.X86%\Windows Kits\8.1"
if not defined MSVS2013_FOLDER set "MSVS2013_FOLDER=%PROGRAMS_FOLDER.X86%\msvs2013"
set "PATH=%MSVS2013_FOLDER%\VC\bin\x86_arm;%MSVS2013_FOLDER%\VC\bin;%MSVS2013_FOLDER%\Common7\IDE;%PATH%"
